/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.2
 * Generated at: 2026-06-28 21:12:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.util.Properties;
import java.io.InputStream;

public final class art_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.Properties");
    _jspx_imports_classes.add("java.io.InputStream");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\"/>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"images/favicon.png\"/>\n");
      out.write("    <title>Art — Brarner.M.Alete™</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\"/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"nav\"><div class=\"nav-inner\">\n");
      out.write("    <a href=\"index.jsp\" class=\"nav-brand\"><img src=\"images/mearvk.ltd.logo.left.png\" alt=\"\" style=\"height:40px;vertical-align:middle;margin-right:8px;background:transparent;\"/>Brarner.M.Alete™<img src=\"images/mearvk.ltd.logo.right.png\" alt=\"\" style=\"height:40px;vertical-align:middle;margin-left:8px;background:transparent;\"/></a>\n");
      out.write("    <ul class=\"nav-links\">\n");
      out.write("        <li><a href=\"index.jsp\">Overview</a></li>\n");
      out.write("        <li><a href=\"species.jsp\">Species</a></li>\n");
      out.write("        <li><a href=\"postal.jsp\">Postal</a></li>\n");
      out.write("        <li><a href=\"art.jsp\" class=\"active\">Art</a></li>\n");
      out.write("        <li><a href=\"science.jsp\">Science</a></li>\n");
      out.write("        <li><a href=\"status.jsp\">Status</a></li>\n");
      out.write("    </ul>\n");
      out.write("    <div class=\"nav-actions\"><a href=\"admin/login.xhtml\" class=\"nav-cta\">Admin →</a></div>\n");
      out.write("</div></nav>\n");
      out.write("\n");
      out.write("<section class=\"hero\" style=\"padding:4rem 2rem;\">\n");
      out.write("    <div class=\"hero-inner\">\n");
      out.write("        <span class=\"hero-tag\">Museum Collections</span>\n");
      out.write("        <h1>Art Database</h1>\n");
      out.write("        <p>Art museum collections indexer covering 22 major institutions with species-linked natural art references.</p>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<section class=\"section\">\n");
      out.write("    <div class=\"section-inner\">\n");

    Connection conn = null;
    try {
        Properties dbProps = new Properties();
        InputStream dbIn = application.getResourceAsStream("/WEB-INF/db.properties");
        if (dbIn != null) { dbProps.load(dbIn); dbIn.close(); }
        Class.forName(dbProps.getProperty("db.driver", "com.mysql.cj.jdbc.Driver"));
        conn = DriverManager.getConnection(
            dbProps.getProperty("db.url", "jdbc:mysql://localhost:3306/BrarnerScience"),
            dbProps.getProperty("db.user", "root"),
            dbProps.getProperty("db.password", ""));

        String museum = request.getParameter("museum");
        if (museum != null && !museum.isEmpty()) {
            PreparedStatement ps = conn.prepareStatement(
                "SELECT title, artist, year_created, medium FROM art_works WHERE museum_name=? ORDER BY title LIMIT 200");
            ps.setString(1, museum);
            ResultSet rs = ps.executeQuery();

      out.write("\n");
      out.write("        <h3>Works at ");
      out.print( museum );
      out.write("</h3>\n");
      out.write("        <p><a href=\"art.jsp\">← Back to museums</a></p>\n");
      out.write("        <div class=\"table-wrap\">\n");
      out.write("            <table>\n");
      out.write("                <thead><tr><th>Title</th><th>Artist</th><th>Year</th><th>Medium</th></tr></thead>\n");
      out.write("                <tbody>\n");

            boolean hasRows = false;
            while (rs.next()) { hasRows = true; 
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>");
      out.print( rs.getString("title") != null ? rs.getString("title") : "" );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("artist") != null ? rs.getString("artist") : "" );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("year_created") != null ? rs.getString("year_created") : "" );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("medium") != null ? rs.getString("medium") : "" );
      out.write("</td>\n");
      out.write("                    </tr>\n");
          }
            if (!hasRows) { 
      out.write("\n");
      out.write("                    <tr><td colspan=\"4\">No works found.</td></tr>\n");
          } rs.close(); ps.close();

      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");

        } else {
            PreparedStatement ps = conn.prepareStatement(
                "SELECT museum_name, COUNT(*) AS works FROM art_works WHERE museum_name IS NOT NULL GROUP BY museum_name ORDER BY museum_name");
            ResultSet rs = ps.executeQuery();

      out.write("\n");
      out.write("        <h3>Museums</h3>\n");
      out.write("        <div class=\"table-wrap\">\n");
      out.write("            <table>\n");
      out.write("                <thead><tr><th>Museum</th><th>Works</th></tr></thead>\n");
      out.write("                <tbody>\n");

            boolean hasRows = false;
            while (rs.next()) { hasRows = true; String m = rs.getString("museum_name"); 
      out.write("\n");
      out.write("                    <tr><td><a href=\"art.jsp?museum=");
      out.print( java.net.URLEncoder.encode(m, "UTF-8") );
      out.write('"');
      out.write('>');
      out.print( m );
      out.write("</a></td><td>");
      out.print( rs.getInt("works") );
      out.write("</td></tr>\n");
          }
            if (!hasRows) { 
      out.write("\n");
      out.write("                    <tr><td colspan=\"2\">No art data available.</td></tr>\n");
          } rs.close(); ps.close();

      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");

        }
    } catch (Exception e) { 
      out.write("\n");
      out.write("        <p style=\"color:#ef4444;\">Database error: ");
      out.print( e.getMessage() != null ? e.getMessage().replace("<","&lt;") : "unknown" );
      out.write("</p>\n");
  } finally { if (conn != null) try { conn.close(); } catch (Exception ignored) {} }

      out.write("\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer class=\"footer\"><div class=\"footer-bottom\" style=\"border:none;padding:0;\">\n");
      out.write("    <span>&#169; 2026 MEARVK LLC. All rights reserved.</span>\n");
      out.write("</div></footer>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
