/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.2
 * Generated at: 2026-06-29 01:17:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import java.util.Properties;
import java.io.*;
import java.nio.file.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("java.nio.file");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.Properties");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

    String message = null;
    String messageColor = "#ef4444";
    String clientIp = request.getHeader("X-Forwarded-For");
    if (clientIp == null || clientIp.isEmpty()) clientIp = request.getRemoteAddr();

    // Handle multipart form submission
    if ("POST".equalsIgnoreCase(request.getMethod()) && request.getContentType() != null && request.getContentType().contains("multipart")) {
        String displayName = "";
        byte[] keyData = null;
        String keyFilename = "";

        // Parse multipart manually (no external lib needed)
        ServletInputStream sis = request.getInputStream();
        String boundary = request.getContentType().split("boundary=")[1];
        String line;
        BufferedReader br = new BufferedReader(new InputStreamReader(sis, "UTF-8"));
        StringBuilder currentField = null;
        String currentFieldName = null;
        boolean inFile = false;
        ByteArrayOutputStream fileBytes = new ByteArrayOutputStream();

        // Use Part API (Servlet 3.0+)
        try {
            displayName = request.getParameter("display_name");
            jakarta.servlet.http.Part filePart = request.getPart("auth_key");
            if (filePart != null && filePart.getSize() > 0) {
                keyFilename = Paths.get(filePart.getSubmittedFileName()).getFileName().toString();
                InputStream fis = filePart.getInputStream();
                keyData = fis.readAllBytes();
                fis.close();
            }
        } catch (Exception pe) {
            // fallback
            message = "Upload error: " + pe.getMessage();
        }

        if (displayName == null || displayName.trim().isEmpty()) {
            displayName = request.getParameter("display_name");
        }

        if (message == null && displayName != null && !displayName.trim().isEmpty()) {
            // Save registration
            Properties dbProps = new Properties();
            InputStream dbIn = application.getResourceAsStream("/WEB-INF/db.properties");
            if (dbIn != null) { dbProps.load(dbIn); dbIn.close(); }
            else {
                String[] tryPaths = { "/opt/tomcat/webapps/brarner.m.alete/WEB-INF/db.properties" };
                for (String tp : tryPaths) { File f = new File(tp);
                    if (f.exists()) { FileInputStream fi = new FileInputStream(f); dbProps.load(fi); fi.close(); break; } }
            }

            Connection conn = null;
            try {
                Class.forName(dbProps.getProperty("db.driver", "com.mysql.cj.jdbc.Driver"));
                conn = DriverManager.getConnection(
                    dbProps.getProperty("db.url", "jdbc:mysql://127.0.0.1:3306/BrarnerScience"),
                    dbProps.getProperty("db.user", "root"),
                    dbProps.getProperty("db.password", ""));

                // Create table if not exists
                conn.createStatement().executeUpdate(
                    "CREATE TABLE IF NOT EXISTS registrations (" +
                    "id INT AUTO_INCREMENT PRIMARY KEY, " +
                    "display_name VARCHAR(255) NOT NULL, " +
                    "ip_address VARCHAR(45) NOT NULL, " +
                    "auth_key MEDIUMBLOB, " +
                    "key_filename VARCHAR(255), " +
                    "authorized BOOLEAN DEFAULT FALSE, " +
                    "registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");

                PreparedStatement ps = conn.prepareStatement(
                    "INSERT INTO registrations (display_name, ip_address, auth_key, key_filename, authorized) VALUES (?, ?, ?, ?, ?)");
                ps.setString(1, displayName.trim());
                ps.setString(2, clientIp);
                if (keyData != null && keyData.length > 0) {
                    ps.setBytes(3, keyData);
                    ps.setString(4, keyFilename);
                    ps.setBoolean(5, true);
                } else {
                    ps.setNull(3, java.sql.Types.BLOB);
                    ps.setNull(4, java.sql.Types.VARCHAR);
                    ps.setBoolean(5, false);
                }
                ps.executeUpdate();
                ps.close();

                message = "Registered successfully as \"" + displayName.trim() + "\" (IP: " + clientIp + ")" + (keyData != null ? " — Key uploaded, authorized for private work." : "");
                messageColor = "#22c55e";
            } catch (Exception e) {
                message = "Registration error: " + (e.getMessage() != null ? e.getMessage().replace("<","&lt;") : "unknown");
            } finally {
                if (conn != null) try { conn.close(); } catch (Exception ignored) {}
            }
        } else if (message == null) {
            message = "Display name is required.";
        }
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\"/>\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"/>\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"images/favicon.png\"/>\n");
      out.write("    <title>Register — Brarner.M.Alete™</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/style.css\"/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"nav\"><div class=\"nav-inner\">\n");
      out.write("    <a href=\"index.jsp\" class=\"nav-brand\"><img src=\"images/mearvk.ltd.logo.left.png\" alt=\"\" style=\"height:40px;vertical-align:middle;margin-right:8px;background:transparent;\"/>Brarner.M.Alete™<img src=\"images/mearvk.ltd.logo.right.png\" alt=\"\" style=\"height:40px;vertical-align:middle;margin-left:8px;background:transparent;\"/></a>\n");
      out.write("    <ul class=\"nav-links\">\n");
      out.write("        <li><a href=\"index.jsp\">Overview</a></li>\n");
      out.write("        <li><a href=\"species.jsp\">Species</a></li>\n");
      out.write("        <li><a href=\"postal.jsp\">Postal</a></li>\n");
      out.write("        <li><a href=\"art.jsp\">Art</a></li>\n");
      out.write("        <li><a href=\"science.jsp\">Science</a></li>\n");
      out.write("        <li><a href=\"status.jsp\">Status</a></li>\n");
      out.write("    </ul>\n");
      out.write("    <div class=\"nav-actions\">\n");
      out.write("        <a href=\"guest.jsp\" class=\"nav-cta\">Guest</a>\n");
      out.write("        <span class=\"nav-cta\" style=\"opacity:0.7;cursor:default;\">Register</span>\n");
      out.write("        <a href=\"admin/login.xhtml\" class=\"nav-cta\">Admin →</a>\n");
      out.write("    </div>\n");
      out.write("</div></nav>\n");
      out.write("\n");
      out.write("<section class=\"hero\" style=\"padding:4rem 2rem;\">\n");
      out.write("    <div class=\"hero-inner\">\n");
      out.write("        <span class=\"hero-tag\">Account Registration</span>\n");
      out.write("        <h1>Register</h1>\n");
      out.write("        <p>Register your identity. Upload an authorization key for private work access.</p>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<section class=\"section\">\n");
      out.write("    <div class=\"section-inner\" style=\"max-width:520px;\">\n");
 if (message != null) { 
      out.write("\n");
      out.write("        <div style=\"padding:1rem;border:1px solid ");
      out.print( messageColor );
      out.write(";border-radius:8px;margin-bottom:1.5rem;background:rgba(0,0,0,0.2);\">\n");
      out.write("            <p style=\"color:");
      out.print( messageColor );
      out.write(";margin:0;font-size:0.9rem;\">");
      out.print( message );
      out.write("</p>\n");
      out.write("        </div>\n");
 } 
      out.write("\n");
      out.write("        <form method=\"post\" enctype=\"multipart/form-data\" action=\"register.jsp\">\n");
      out.write("            <div style=\"margin-bottom:1.25rem;\">\n");
      out.write("                <label style=\"display:block;font-size:0.8rem;color:#a1a1aa;margin-bottom:0.35rem;\">Display Name *</label>\n");
      out.write("                <input type=\"text\" name=\"display_name\" required placeholder=\"Your name or handle\" style=\"width:100%;padding:0.6rem 0.75rem;background:#1a1a24;border:1px solid #27272a;border-radius:8px;color:#fff;font-size:0.9rem;\"/>\n");
      out.write("            </div>\n");
      out.write("            <div style=\"margin-bottom:1.25rem;\">\n");
      out.write("                <label style=\"display:block;font-size:0.8rem;color:#a1a1aa;margin-bottom:0.35rem;\">Your IP Address</label>\n");
      out.write("                <input type=\"text\" value=\"");
      out.print( clientIp );
      out.write("\" readonly style=\"width:100%;padding:0.6rem 0.75rem;background:#0a0a0f;border:1px solid #27272a;border-radius:8px;color:#71717a;font-size:0.9rem;\"/>\n");
      out.write("            </div>\n");
      out.write("            <div style=\"margin-bottom:1.25rem;\">\n");
      out.write("                <label style=\"display:block;font-size:0.8rem;color:#a1a1aa;margin-bottom:0.35rem;\">Authorization Key (file upload, optional)</label>\n");
      out.write("                <input type=\"file\" name=\"auth_key\" accept=\".key,.pem,.pub,.txt\" style=\"width:100%;padding:0.5rem;background:#1a1a24;border:1px solid #27272a;border-radius:8px;color:#a1a1aa;font-size:0.85rem;\"/>\n");
      out.write("                <p style=\"font-size:0.75rem;color:#71717a;margin-top:0.35rem;\">Upload your public.key or authorization key for private work access. Without a key, you register as a public guest.</p>\n");
      out.write("            </div>\n");
      out.write("            <button type=\"submit\" style=\"width:100%;padding:0.7rem;background:#3b82f6;color:#fff;border:none;border-radius:8px;font-size:0.9rem;font-weight:600;cursor:pointer;\">Register</button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer class=\"footer\"><div class=\"footer-bottom\" style=\"border:none;padding:0;\">\n");
      out.write("    <span>&#169; 2026 MEARVK LLC. All rights reserved.</span>\n");
      out.write("</div></footer>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
