#!/bin/bash
# NitroWebExpress™ — Post-Clone Setup (Linux)
# Run once after cloning the repository. Installs dependencies, deploys all webapps.
# Usage: sudo bash scripts/web/post-clone.sh
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(dirname "$(dirname "$SCRIPT_DIR")")"

echo "═══════════════════════════════════════════════════════════════"
echo " NitroWebExpress™ — Post-Clone Setup (Linux)"
echo "═══════════════════════════════════════════════════════════════"
echo ""

# ── 0. Database Credentials ───────────────────────────────────────────────────
# Prompt for MySQL password upfront so the rest of the install runs unattended.
if [ -f "$PROJECT_ROOT/.nwe-credentials" ]; then
    source "$PROJECT_ROOT/.nwe-credentials"
    echo "[*] Loaded existing credentials from .nwe-credentials"
    echo "    User: ${NWE_DB_USER:-root}  Host: ${NWE_DB_HOST:-127.0.0.1}:${NWE_DB_PORT:-3306}"
    echo ""
else
    echo "┌────────────────────────────────────────────────────────────────────"
    echo "│ MySQL Database Credentials"
    echo "│ These will be used for all module databases and JSP pages."
    echo "│ Saved to .nwe-credentials (chmod 600, gitignored)."
    echo "└────────────────────────────────────────────────────────────────────"
    echo ""
    read -rp "  MySQL user [root]: " NWE_DB_USER
    NWE_DB_USER="${NWE_DB_USER:-root}"
    read -rsp "  MySQL password: " NWE_DB_PASS
    echo ""
    read -rp "  MySQL host [127.0.0.1]: " NWE_DB_HOST
    NWE_DB_HOST="${NWE_DB_HOST:-127.0.0.1}"
    read -rp "  MySQL port [3306]: " NWE_DB_PORT
    NWE_DB_PORT="${NWE_DB_PORT:-3306}"
    echo ""

    # Write credentials file
    cat > "$PROJECT_ROOT/.nwe-credentials" <<EOF
# NWE Local Credentials — generated by post-clone.sh
# NEVER COMMIT THIS FILE (it is .gitignored)
NWE_DB_HOST="$NWE_DB_HOST"
NWE_DB_PORT="$NWE_DB_PORT"
NWE_DB_USER="$NWE_DB_USER"
NWE_DB_PASS='$NWE_DB_PASS'
EOF
    chmod 600 "$PROJECT_ROOT/.nwe-credentials"
    echo "[OK] Credentials saved to .nwe-credentials (mode 600)"
    echo ""
fi

export NWE_DB_HOST NWE_DB_PORT NWE_DB_USER NWE_DB_PASS

# 1. Ensure Java 21
if ! java -version 2>&1 | grep -q "21\|22\|23"; then
    echo "[*] Installing Java 21..."
    apt update -qq && apt install -y -qq openjdk-21-jre-headless 2>/dev/null || \
    dnf install -y java-21-openjdk-headless 2>/dev/null || true
fi
echo "[OK] Java: $(java -version 2>&1 | head -1)"

# 2. Ensure MySQL
if ! command -v mysql &>/dev/null; then
    echo "[*] Installing MySQL..."
    apt install -y -qq mysql-server 2>/dev/null || dnf install -y mysql-server 2>/dev/null || true
    systemctl enable mysql 2>/dev/null || systemctl enable mysqld 2>/dev/null
fi
# Always ensure MySQL is running (may be installed but stopped after reboot)
echo "[*] Starting MySQL service..."
systemctl start mysql 2>/dev/null || systemctl start mysqld 2>/dev/null || true
echo "[OK] MySQL: $(mysql --version 2>/dev/null | head -1)"

# 3. Configure MySQL root for JDBC
echo "[*] Configuring MySQL root for JDBC (caching_sha2_password)..."
sudo mysql -e "ALTER USER '${NWE_DB_USER:-root}'@'localhost' IDENTIFIED WITH caching_sha2_password BY '${NWE_DB_PASS}'; FLUSH PRIVILEGES;" 2>/dev/null || true
echo "[OK] MySQL password configured for user=${NWE_DB_USER:-root}"

# 4. Ensure Tomcat
TOMCAT_HOME="/home/mearvk/tomcat"
if [ ! -f "$TOMCAT_HOME/bin/catalina.sh" ]; then
    echo "[*] Installing Tomcat 11..."
    cd /tmp && curl -sfLO "https://archive.apache.org/dist/tomcat/tomcat-11/v11.0.2/bin/apache-tomcat-11.0.2.tar.gz"

    # SECURITY: Verify download integrity before extracting.
    # Tomcat archives have been targeted by supply-chain attacks in the past.
    # SHA-512 hash sourced from https://archive.apache.org/dist/tomcat/tomcat-11/v11.0.2/bin/apache-tomcat-11.0.2.tar.gz.sha512
    echo "[*] Verifying Tomcat SHA-512 checksum..."
    TOMCAT_SHA512_URL="https://archive.apache.org/dist/tomcat/tomcat-11/v11.0.2/bin/apache-tomcat-11.0.2.tar.gz.sha512"
    EXPECTED_SHA512=$(curl -sfL "$TOMCAT_SHA512_URL" | awk '{print $1}')
    ACTUAL_SHA512=$(sha512sum /tmp/apache-tomcat-11.0.2.tar.gz | awk '{print $1}')
    if [ -z "$EXPECTED_SHA512" ]; then
        echo "[WARN] Could not fetch SHA-512 from Apache — skipping verification (network issue?)"
    elif [ "$ACTUAL_SHA512" != "$EXPECTED_SHA512" ]; then
        echo "[ERROR] SHA-512 MISMATCH! Downloaded Tomcat archive may be corrupted or tampered with."
        echo "        Expected: $EXPECTED_SHA512"
        echo "        Actual:   $ACTUAL_SHA512"
        echo "        Aborting Tomcat installation. Remove /tmp/apache-tomcat-11.0.2.tar.gz and retry."
        rm -f /tmp/apache-tomcat-11.0.2.tar.gz
        exit 1
    else
        echo "[OK] SHA-512 verified"
    fi

    mkdir -p "$TOMCAT_HOME" && tar -xzf apache-tomcat-11.0.2.tar.gz -C "$TOMCAT_HOME" --strip-components=1
    rm -f apache-tomcat-11.0.2.tar.gz
    id tomcat &>/dev/null || useradd -r -M -d "$TOMCAT_HOME" -s /bin/false tomcat
    chown -R tomcat:tomcat "$TOMCAT_HOME" && chmod +x "$TOMCAT_HOME"/bin/*.sh
fi
echo "[OK] Tomcat: $TOMCAT_HOME"

# 5. Make all scripts executable
find "$PROJECT_ROOT" -name "*.sh" -exec chmod +x {} \;
echo "[OK] Scripts: chmod +x applied"

# 5.1. Install UFW and open all NWE ports
echo ""
echo "[*] Configuring firewall — installing UFW and opening all NWE service ports..."
source "$PROJECT_ROOT/scripts/nwe-ports.sh"
nwe_ensure_ufw
nwe_open_ports
echo "[OK] Firewall configured"

# 5.5. Setup module databases (safe — uses CREATE IF NOT EXISTS, never drops)
echo ""
echo "[*] Setting up module databases (non-destructive — existing data preserved)..."

# Wait for MySQL to be fully ready before running setup scripts
echo "[*] Waiting for MySQL to accept connections..."
for i in $(seq 1 30); do
    if mysql -u "$NWE_DB_USER" -p"$NWE_DB_PASS" -h "${NWE_DB_HOST:-127.0.0.1}" -P "${NWE_DB_PORT:-3306}" -e "SELECT 1" &>/dev/null; then
        echo "[OK] MySQL is ready (attempt $i)"
        break
    fi
    if [ "$i" -eq 30 ]; then
        echo "[ERROR] MySQL did not become ready within 30 seconds. Skipping database setup."
        echo "        Run manually: bash scripts/web/setup-all-databases.sh"
    fi
    sleep 1
done
echo ""
echo "    ┌─────────────────────────────────────────────────────────────"
echo "    │  Database                     Module"
echo "    ├─────────────────────────────────────────────────────────────"
echo "    │  nwe_california_fbi           California FBI"
echo "    │  nwe_california_cia           California CIA"
echo "    │  nwe_california_nsa           California NSA"
echo "    │  nwe_duke                     Duke University"
echo "    │  nwe_library                  Stanford Library"
echo "    │  nwe_ae6e66                   AE6E66 (UK Parliament)"
echo "    │  nwe_futures                  Futures (Democratic AI)"
echo "    │  nwe_gdgh                     Green Durham Grass and Herb"
echo "    │  nwe_gray_registry            Gray Port Registry"
echo "    │  nwe_gray85_registry          Gray85 Crème Registry"
echo "    │  nwe_blackbelt                Black Belt"
echo "    │  nwe_languages                Languages"
echo "    │  nwe_strernary                Strernary (AI Inference)"
echo "    │  nwe_integrity                Integrity System"
echo "    │  BrarnerScience               Brarner.M.Alete"
echo "    └─────────────────────────────────────────────────────────────"
echo ""

# Export MYSQL_PWD so child setup scripts can connect without -p on command line
export MYSQL_PWD="$NWE_DB_PASS"

SETUP_SCRIPTS=(
    "modules/fbi/servlets/setup-db.sh"
    "modules/cia/servlets/setup-db.sh"
    "modules/nsa/servlets/setup-db.sh"
    "modules/duke/servlets/setup-db.sh"
    "modules/library/servlets/setup-db.sh"
    "modules/AE6E66/servlets/setup-db.sh"
    "modules/red/Futures/servlets/setup-db.sh"
    "modules/Green.Durham.Grass.and.Herb/servlets/setup-db.sh"
)
for SETUP in "${SETUP_SCRIPTS[@]}"; do
    FULL="$PROJECT_ROOT/$SETUP"
    if [ -f "$FULL" ]; then
        timeout 30 bash "$FULL" 2>/dev/null && echo "  [OK] $SETUP" || echo "  [WARN] $SETUP (timeout or MySQL not ready)"
    fi
done

unset MYSQL_PWD

# 6. Deploy all web modules (30s timeout per module, inline for reliability)
echo ""
echo "[*] Deploying all web modules (30s timeout each)..."
echo ""

DEPLOY_PASS=0
DEPLOY_FAIL=0
DEPLOY_SCRIPTS=(
    "modules/AE6E66/servlets/deploy-local.sh"
    "modules/fbi/servlets/deploy-local.sh"
    "modules/cia/servlets/deploy-local.sh"
    "modules/nsa/servlets/deploy-local.sh"
    "modules/duke/servlets/deploy-local.sh"
    "modules/library/servlets/deploy-local.sh"
    "modules/gray/servlets/deploy-local.sh"
    "modules/gray.a85/servlets/deploy-local.sh"
    "modules/black-belt/servlets/deploy-local.sh"
    "modules/languages/servlets/deploy-local.sh"
    "modules/Green.Durham.Grass.and.Herb/servlets/deploy-local.sh"
    "modules/red/Futures/servlets/deploy-local.sh"
    "source/strernary/servlets/deploy-local.sh"
    "modules/black/presidential/Brarner.M.Alete/install/deploy-local.sh"
)

set +e  # Disable exit-on-error for deploy loop (individual failures are handled)
for DS in "${DEPLOY_SCRIPTS[@]}"; do
    FULL="$PROJECT_ROOT/$DS"
    MODULE_NAME=$(echo "$DS" | sed 's|modules/||;s|/servlets.*||;s|/install.*||;s|source/||')
    if [ ! -f "$FULL" ]; then
        echo "  [SKIP] $MODULE_NAME — script not found"
        continue
    fi
    echo -n "  [*] $MODULE_NAME... "
    DEPLOY_OUT=$(timeout 30 bash "$FULL" "$TOMCAT_HOME" </dev/null 2>&1)
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 0 ]; then
        echo "✓"
        DEPLOY_PASS=$((DEPLOY_PASS + 1))
    elif [ $EXIT_CODE -eq 124 ]; then
        echo "TIMEOUT (30s) — skipping"
        DEPLOY_FAIL=$((DEPLOY_FAIL + 1))
    else
        echo "✗ (exit $EXIT_CODE)"
        DEPLOY_FAIL=$((DEPLOY_FAIL + 1))
    fi
done
set -e  # Re-enable exit-on-error

echo ""
echo "[OK] Deployed: $DEPLOY_PASS | Failed: $DEPLOY_FAIL"

# 7. Start Tomcat
systemctl start tomcat 2>/dev/null || "$TOMCAT_HOME/bin/startup.sh"
echo "[OK] Tomcat started"

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo " Post-clone setup complete."
echo " All modules: http://localhost:8080/"
echo "═══════════════════════════════════════════════════════════════"
